apiVersion: konnektr.io/v1alpha1
kind: DatabaseQueryResource
metadata:
  name: namespace-dbqr
  namespace: ktrlplane
  finalizers:
    - konnektr.io/databasequeryresource-finalizer
spec:
  # How often to query the database and reconcile
  pollInterval: "5m"
  # Whether to delete resources if their corresponding DB row disappears (default: true)
  prune: true
  database:
    type: postgres
    connectionSecretRef:
      name: ktrlplane-db-app
      uriKey: uri
  # The SQL query to execute
  query: "SELECT project_id, org_id FROM ktrlplane.projects;"
  # Go template for the Kubernetes resource(s)
  template: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: {{ .Row.project_id | lower }}
      labels:
        konnektr.io/project-id: {{ .Row.project_id | lower }}
        konnektr.io/org-id: {{ .Row.org_id | lower }}
