apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-porkbun-webhook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: https://charts.konnektr.io
    targetRevision: "0.1.5"
    chart: porkbun-webhook
    helm:
      valuesObject:
        nodeSelector:
          cloud.google.com/gke-spot: "true"
        terminationGracePeriodSeconds: 15
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
