apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: porkbun-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: porkbun-secret
    creationPolicy: Owner
  data:
  - secretKey: APIKEY
    remoteRef:
      key: porkbun-apikey
  - secretKey: SECRETAPIKEY
    remoteRef:
      key: porkbun-secretapikey