# OIDC config for ArgoCD SSO (edit values for Auth0 or Google Cloud Identity)
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.konnektr.io
  timeout.reconciliation: 1h # Reduce frequency of repo polling
  timeout.reconciliation.jitter: 5m # Add some jitter to avoid thundering herd
  oidc.config: |
    name: Auth0
    issuer: https://auth.konnektr.io/ 
    clientID: 90TsN4J1Y1KQ1NWgy8PJjKp3mx7lH6Ig  
    clientSecret: $oidc.auth0.clientSecret
    requestedScopes: [openid, profile, email, groups]
    requestedIDTokenClaims:
      groups:
        essential: true
    # Optional: Configure group claims from Auth0
    # claimsMapping:
    #   groups: https://argocd.io/groups