# OIDC config for ArgoCD SSO (edit values for Auth0 or Google Cloud Identity)
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: --enable-helm
  url: https://argocd.konnektr.io
  timeout.reconciliation: 24h # Polling frequency (reduced since webhooks handle most updates)
  timeout.reconciliation.jitter: 1h # Add some jitter to avoid thundering herd
  # Webhook configuration
  webhook.github.secret: $webhook.github.secret
  exec.enabled: "true"
  oidc.config: |
    name: Auth0
    issuer: https://auth.konnektr.io/ 
    clientID: 90TsN4J1Y1KQ1NWgy8PJjKp3mx7lH6Ig  
    clientSecret: $oidc.auth0.clientSecret
    requestedScopes: [openid, profile, email, groups]
    requestedIDTokenClaims:
      groups:
        essential: true
    claimsMapping:
      groups: https://konnektr.io/groups
  policy.default: role:none
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, repositories, get, *, allow
    g, konnektr-admins, role:admin
    g, konnektr-developers, role:developer