apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook-secret
  namespace: argocd
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge # Merge with existing argocd-secret (for Auth0)
    template:
      type: Opaque
      mergePolicy: Merge
      data:
        # This will be used in argocd-cm.yaml as $webhook.github.secret
        webhook.github.secret: "{{ .githubWebhookSecret }}"
  data:
    - secretKey: githubWebhookSecret
      remoteRef:
        key: argocd-github-webhook-secret # Name of the secret in Google Secret Manager
