apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"envoy-gateway-system","namespace":"argocd"},"spec":{"destination":{"namespace":"envoy-gateway","server":"https://kubernetes.default.svc"},"project":"platform","source":{"helm":{"valuesObject":{"deployment":{"envoyGateway":{"pod":{"nodeSelector":{"cloud.google.com/gke-spot":"true"},"terminationGracePeriodSeconds":15}}},"extProc":{"extraEnvVars":[{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://platform-collector.opentelemetry.svc.cluster.local:4317"},{"name":"OTEL_EXPORTER_OTLP_PROTOCOL","value":"grpc"},{"name":"OTEL_SERVICE_NAME","value":"envoy-gateway"}]}}},"path":".","repoURL":"oci://docker.io/envoyproxy/gateway-helm","targetRevision":"1.5.1"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["ServerSideApply=true","CreateNamespace=true"]}}}
  creationTimestamp: "2025-10-19T18:10:45Z"
  generation: 16
  name: envoy-gateway-system
  namespace: argocd
  resourceVersion: "1760897490240047006"
  uid: 7e0cb7f9-e68e-4a09-91be-7c656a8a00e9
operation:
  initiatedBy:
    automated: true
  retry:
    limit: 5
  sync:
    prune: true
    revision: sha256:aed23af13a47861d492bc8e9a078d9bdc0d9b5b0d83683f4f47bad83be5b6ace
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
spec:
  destination:
    namespace: envoy-gateway
    server: https://kubernetes.default.svc
  project: platform
  source:
    helm:
      valuesObject:
        deployment:
          pod:
            nodeSelector:
              cloud.google.com/gke-spot: "true"
        extProc:
          extraEnvVars:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://platform-collector.opentelemetry.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: envoy-gateway
    path: .
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: 1.5.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-10-19T18:10:47Z"
    status: Missing
  operationState:
    message: waiting for completion of hook batch/Job/envoy-gateway-system-gateway-helm-certgen
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: sha256:aed23af13a47861d492bc8e9a078d9bdc0d9b5b0d83683f4f47bad83be5b6ace
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
    phase: Running
    startedAt: "2025-10-19T18:10:47Z"
    syncResult:
      resources:
        - group: ""
          hookPhase: Succeeded
          hookType: PreSync
          kind: ServiceAccount
          message: envoy-gateway-system-gateway-helm-certgen created
          name: envoy-gateway-system-gateway-helm-certgen
          namespace: envoy-gateway
          syncPhase: PreSync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Succeeded
          hookType: PreSync
          kind: ClusterRole
          message: envoy-gateway-system-gateway-helm-certgen:envoy-gateway created
          name: envoy-gateway-system-gateway-helm-certgen:envoy-gateway
          namespace: envoy-gateway
          syncPhase: PreSync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Succeeded
          hookType: PreSync
          kind: ClusterRoleBinding
          message: envoy-gateway-system-gateway-helm-certgen:envoy-gateway created
          name: envoy-gateway-system-gateway-helm-certgen:envoy-gateway
          namespace: envoy-gateway
          syncPhase: PreSync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Succeeded
          hookType: PreSync
          kind: Role
          message: envoy-gateway-system-gateway-helm-certgen created
          name: envoy-gateway-system-gateway-helm-certgen
          namespace: envoy-gateway
          syncPhase: PreSync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Succeeded
          hookType: PreSync
          kind: RoleBinding
          message: envoy-gateway-system-gateway-helm-certgen created
          name: envoy-gateway-system-gateway-helm-certgen
          namespace: envoy-gateway
          syncPhase: PreSync
          version: v1
        - group: admissionregistration.k8s.io
          hookPhase: Succeeded
          hookType: PreSync
          kind: MutatingWebhookConfiguration
          message: envoy-gateway-topology-injector.envoy-gateway created
          name: envoy-gateway-topology-injector.envoy-gateway
          namespace: envoy-gateway
          syncPhase: PreSync
          version: v1
        - group: batch
          hookPhase: Running
          hookType: PreSync
          images:
            - docker.io/envoyproxy/gateway:v1.5.1
          kind: Job
          message: job.batch/envoy-gateway-system-gateway-helm-certgen serverside-applied
          name: envoy-gateway-system-gateway-helm-certgen
          namespace: envoy-gateway
          syncPhase: PreSync
          version: v1
      revision: sha256:aed23af13a47861d492bc8e9a078d9bdc0d9b5b0d83683f4f47bad83be5b6ace
      source:
        helm:
          valuesObject:
            deployment:
              envoyGateway:
                pod:
                  nodeSelector:
                    cloud.google.com/gke-spot: "true"
                  terminationGracePeriodSeconds: 15
            extProc:
              extraEnvVars:
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: http://platform-collector.opentelemetry.svc.cluster.local:4317
                - name: OTEL_EXPORTER_OTLP_PROTOCOL
                  value: grpc
                - name: OTEL_SERVICE_NAME
                  value: envoy-gateway
        path: .
        repoURL: oci://docker.io/envoyproxy/gateway-helm
        targetRevision: 1.5.1
  reconciledAt: "2025-10-19T18:10:45Z"
  resourceHealthSource: appTree
  resources:
    - kind: ConfigMap
      name: envoy-gateway-config
      namespace: envoy-gateway
      status: Synced
      version: v1
    - kind: Service
      name: envoy-gateway
      namespace: envoy-gateway
      status: OutOfSync
      version: v1
    - kind: ServiceAccount
      name: envoy-gateway
      namespace: envoy-gateway
      status: Synced
      version: v1
    - hook: true
      kind: ServiceAccount
      name: envoy-gateway-system-gateway-helm-certgen
      namespace: envoy-gateway
      requiresPruning: true
      version: v1
    - group: admissionregistration.k8s.io
      hook: true
      kind: MutatingWebhookConfiguration
      name: envoy-gateway-topology-injector.envoy-gateway
      requiresPruning: true
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: backends.gateway.envoyproxy.io
      status: Synced
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: backendtlspolicies.gateway.networking.k8s.io
      status: Synced
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: backendtrafficpolicies.gateway.envoyproxy.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clienttrafficpolicies.gateway.envoyproxy.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: envoyextensionpolicies.gateway.envoyproxy.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: envoypatchpolicies.gateway.envoyproxy.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: envoyproxies.gateway.envoyproxy.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: gatewayclasses.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: gateways.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: grpcroutes.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: httproutefilters.gateway.envoyproxy.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: httproutes.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: referencegrants.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: securitypolicies.gateway.envoyproxy.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: tcproutes.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: tlsroutes.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: udproutes.gateway.networking.k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: xbackendtrafficpolicies.gateway.networking.x-k8s.io
      status: OutOfSync
      version: v1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: xlistenersets.gateway.networking.x-k8s.io
      status: OutOfSync
      version: v1
    - group: apps
      kind: Deployment
      name: envoy-gateway
      namespace: envoy-gateway
      status: OutOfSync
      version: v1
    - group: batch
      hook: true
      kind: Job
      name: envoy-gateway-system-gateway-helm-certgen
      namespace: envoy-gateway
      requiresPruning: true
      version: v1
    - group: rbac.authorization.k8s.io
      hook: true
      kind: ClusterRole
      name: envoy-gateway-system-gateway-helm-certgen:envoy-gateway
      requiresPruning: true
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: envoy-gateway-system-gateway-helm-envoy-gateway-role
      status: OutOfSync
      version: v1
    - group: rbac.authorization.k8s.io
      hook: true
      kind: ClusterRoleBinding
      name: envoy-gateway-system-gateway-helm-certgen:envoy-gateway
      requiresPruning: true
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: envoy-gateway-system-gateway-helm-envoy-gateway-rolebinding
      status: OutOfSync
      version: v1
    - group: rbac.authorization.k8s.io
      hook: true
      kind: Role
      name: envoy-gateway-system-gateway-helm-certgen
      namespace: envoy-gateway
      requiresPruning: true
      version: v1
    - group: rbac.authorization.k8s.io
      kind: Role
      name: envoy-gateway-system-gateway-helm-infra-manager
      namespace: envoy-gateway
      status: OutOfSync
      version: v1
    - group: rbac.authorization.k8s.io
      kind: Role
      name: envoy-gateway-system-gateway-helm-leader-election-role
      namespace: envoy-gateway
      status: OutOfSync
      version: v1
    - group: rbac.authorization.k8s.io
      hook: true
      kind: RoleBinding
      name: envoy-gateway-system-gateway-helm-certgen
      namespace: envoy-gateway
      requiresPruning: true
      version: v1
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: envoy-gateway-system-gateway-helm-infra-manager
      namespace: envoy-gateway
      status: OutOfSync
      version: v1
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: envoy-gateway-system-gateway-helm-leader-election-rolebinding
      namespace: envoy-gateway
      status: OutOfSync
      version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    images:
      - docker.io/envoyproxy/gateway:v1.5.1
  sync:
    comparedTo:
      destination:
        namespace: envoy-gateway
        server: https://kubernetes.default.svc
      source:
        helm:
          valuesObject:
            deployment:
              envoyGateway:
                pod:
                  nodeSelector:
                    cloud.google.com/gke-spot: "true"
                  terminationGracePeriodSeconds: 15
            extProc:
              extraEnvVars:
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: http://platform-collector.opentelemetry.svc.cluster.local:4317
                - name: OTEL_EXPORTER_OTLP_PROTOCOL
                  value: grpc
                - name: OTEL_SERVICE_NAME
                  value: envoy-gateway
        path: .
        repoURL: oci://docker.io/envoyproxy/gateway-helm
        targetRevision: 1.5.1
    revision: sha256:aed23af13a47861d492bc8e9a078d9bdc0d9b5b0d83683f4f47bad83be5b6ace
    status: OutOfSync
