apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth0-secret
  namespace: argocd
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # This will be used in argocd-cm.yaml as $oidc.auth0.clientSecret
        oidc.auth0.clientSecret: "{{ .auth0ClientSecret }}"
  data:
  - secretKey: auth0ClientSecret
    remoteRef:
      key: argocd-auth0-client-secret  # Name of the secret in Google Secret Manager