apiVersion: v1
kind: Namespace
metadata:
  name: platform
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - name: "*"
      namespace: "*"
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  annotations:
    localSource: "true"
    argocd.argoproj.io/manifest-generate-paths: ../../
spec:
  destination:
    namespace: platform
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: kubernetes/platform/overlays/prd
    repoURL: https://github.com/konnektr-io/infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
