apiVersion: konnektr.io/v1alpha1
kind: DatabaseQueryResource
metadata:
  name: konnektr-project-namespace
  namespace: ktrlplane
  finalizers:
    - konnektr.io/databasequeryresource-finalizer
spec:
  # How often to query the database and reconcile
  pollInterval: "5m"
  # Whether to delete resources if their corresponding DB row disappears (default: true)
  prune: true
  database:
    type: postgres
    connectionSecretRef:
      # Name of the Secret created earlier
      name: ktrlplane-db-secret
      # Optional: Namespace of the Secret (defaults to this CR's namespace)
      # namespace: database-secrets
      # Optional: Override default keys in the Secret
      hostKey: DB_HOST
      portKey: DB_PORT
      userKey: DB_USER
      passwordKey: DB_PASSWORD
      dbNameKey: DB_NAME
      # sslModeKey: DB_SSLMODE
  # The SQL query to execute
  query: "SELECT resource_id, project_id FROM ktrlplane.resources WHERE type = 'Konnektr.Graph';"
  # Go template for the Kubernetes resource(s)
  template: |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: {{ .Row.resource_id | lower }}
      namespace: argocd
    spec:
      chart: graph
      repo: https://charts.konnektr.io
      version: "0.2.5"
      targetNamespace: {{ .Row.project_id | lower }}
      valuesContent: |-
        fullnameOverride: {{ .Row.resource_id | lower }}
        cluster:
          cluster:
            imageName: "apache/age:dev_snapshot_PG17"
            instances: 1
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: cloud.google.com/gke-spot
                      operator: In
                      values:
                      - "true"
            resources:
              limits:
                cpu: "1"
                memory: 2Gi
              requests:
                cpu: 50m
                memory: 1000Mi
        api:
          enabled: true
          # Spot node configuration for API
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          terminationGracePeriodSeconds: 15
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 250Mi
              cpu: 50m
        events:
          enabled: false
