apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ktrlplane
  namespace: ktrlplane
spec:
  chart: ktrlplane
  repo: https://charts.konnektr.io
  version: "0.2.50"
  targetNamespace: ktrlplane
  valuesContent: |-
    database:
      enabled: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"
        external-dns.alpha.kubernetes.io/hostname: ktrlplane.local.raes.konnektr.io
        external-dns.alpha.kubernetes.io/target: "192.168.1.129"
      hosts: 
        - ktrlplane.local.raes.konnektr.io
      tls:
        - secretName: ktrlplane-tls
          hosts:
            - ktrlplane.local.raes.konnektr.io

    stripe:
      enabled: true
      useExternalSecret: true
      externalSecretName: "stripe-secret"
      # Product configuration (safe to store in values)
      products:
        - resource_type: "Konnektr.Graph"
          sku: "free"
          product_id: "prod_T01txFyd6dfzao"
        - resource_type: "Konnektr.Graph"
          sku: "standard"
          product_id: "prod_SzztLZsKSYqiVz"
        - resource_type: "Konnektr.Flow"
          sku: "free"
          product_id: "prod_T0n3Z04EIgDZcT"
        - resource_type: "Konnektr.Flow"
          sku: "standard"
          product_id: "prod_T01up7wLDULGB1"

    db-query-operator:
      enabled: true
      gvkPattern: "helm.cattle.io/v1/HelmChart;v1/ConfigMap"
      includeCRDs: true
