apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Patch external-dns deployment for spot nodes
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: external-dns
        namespace: external-dns
      spec:
        template:
          spec:
            nodeSelector:
              cloud.google.com/gke-spot: "true"
            terminationGracePeriodSeconds: 15
