apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-system
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    path: .
    targetRevision: 1.5.1 # update as needed
    helm:
      valuesObject:
        deployment:
          envoyGateway:
            pod:
              nodeSelector:
                cloud.google.com/gke-spot: "true"
              terminationGracePeriodSeconds: 15
        extProc:
          extraEnvVars:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://platform-collector.opentelemetry.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
  namespace: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
