apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-system
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: 1.5.1 # update as needed
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
