apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: mimir-distributed
    targetRevision: 5.2.0
    helm:
      valuesObject:
        mimir:
          multitenancy_enabled: true
          structuredConfig:
            limits:
              ingestion_rate: 100000
            blocks_storage:
              backend: gcs
              gcs:
                bucket_name: "konnektr-mimir-data" # <-- YOUR GCS BUCKET NAME
                service_account_path: /var/gcs/gcs.json
        # Mount the secret for all Mimir components that access storage
        compactor:
          extraVolumeMounts:
            - name: gcs-credentials
              mountPath: /var/gcs
              readOnly: true
          extraVolumes:
            - name: gcs-credentials
              secret:
                secretName: gcs-credentials
        store_gateway:
          extraVolumeMounts:
            - name: gcs-credentials
              mountPath: /var/gcs
              readOnly: true
          extraVolumes:
            - name: gcs-credentials
              secret:
                secretName: gcs-credentials
        ingester:
          extraVolumeMounts:
            - name: gcs-credentials
              mountPath: /var/gcs
              readOnly: true
          extraVolumes:
            - name: gcs-credentials
              secret:
                secretName: gcs-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
